stages:
  - build
  - test

build:
  stage: build
  image: node:18
  before_script:
    - npm install --legacy-peer-deps
  script:
    - yarn install
    - npm run build
  artifacts:
    paths:
      - dist/
