stages:
  - build
  - test

build:
  stage: build
  image: node:18
  before_script:
    - npm install --legacy-peer-deps
  script:
    - npm run build
  artifacts:
    paths:
      - dist/


test:
  stage: test
  script:
    - npm test
