import type { Metadata } from "next";

import { Toaster } from 'sonner'
import "./globals.css"
import CursorFollower from "./components/cursorFollower";
import DarkModeToggle from "./pages/(public)/(with-navbar)/_components/toggleMode";



export const metadata: Metadata = {
  title: "Simplex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html >
      <body
        className={`antialiased dark:bg-black bg-kwhiteBg w-[100vw] dark:text-white overflow-x-hidden`}
      >
        <Toaster position="top-right" duration={2000}/>
        {/* <I18Providers locale={params.locale}> */}
          {children}
        {/* </I18Providers> */}
        
        <CursorFollower></CursorFollower> 
        <DarkModeToggle></DarkModeToggle>
        
      </body>
    </html>
  );
}
